# -*- coding: utf-8 -*-
"""
Node2Vec + MLP baseline for shared DDI splits.

Design goals for reviewer-required experiments:
1) consume exactly the prepared CSV + shared split NPZ generated by generate_shared_splits.py;
2) do NOT perform any extra train/val/test splitting or negative sampling;
3) learn node2vec embeddings from TRAIN graph only for each split;
4) train an MLP edge classifier for binary / 3-class / 4-class targets;
5) report the same metrics for all splits so that mean/std/significance can be computed.
"""

from __future__ import annotations

import argparse
import json
import math
import os
import random
import re
import time
from collections import defaultdict
from pathlib import Path
from typing import Dict, Iterable, Iterator, List, Optional, Sequence, Tuple

import numpy as np
import pandas as pd
from sklearn.metrics import (
    accuracy_score,
    average_precision_score,
    balanced_accuracy_score,
    f1_score,
    precision_score,
    recall_score,
    roc_auc_score,
)
from sklearn.preprocessing import label_binarize

try:
    from gensim.models import Word2Vec
except Exception as e:  # pragma: no cover
    raise RuntimeError(
        "Failed to import gensim. Install a Python-3 compatible version, e.g.\n"
        "  pip install \"gensim>=4.3,<4.4\" \"scipy>=1.10,<1.13\"\n"
        f"Original error: {repr(e)}"
    )

try:
    import torch
    import torch.nn as nn
    import torch.nn.functional as F
except Exception as e:  # pragma: no cover
    raise RuntimeError(
        "Failed to import torch. Use the same PyTorch environment as your other baselines.\n"
        f"Original error: {repr(e)}"
    )


ID_COL_CANDIDATES_1 = [
    "drug1_id_std", "drug1", "drug1_id", "drug_a", "head", "h",
    "first drug id", "drugbank_id_1"
]

ID_COL_CANDIDATES_2 = [
    "drug2_id_std", "drug2", "drug2_id", "drug_b", "tail", "t",
    "second drug id", "drugbank_id_2"
]

LABEL_COL_CANDIDATES = [
    "label_id", "label", "label_raw", "y", "relation", "class"
]

NEGATIVE_TOKENS = {
    "0", "false", "negative", "neg", "none", "no", "no_interaction",
    "non_interaction", "non-ddi", "non_ddi", "no_ddi", "not_ddi",
}


def set_global_seed(seed: int, deterministic_torch: bool = False) -> None:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    if deterministic_torch:
        torch.backends.cudnn.deterministic = True
        torch.backends.cudnn.benchmark = False


def pick_column(df: pd.DataFrame, candidates: Sequence[str], role: str, user_value: Optional[str]) -> str:
    if user_value:
        if user_value not in df.columns:
            raise ValueError(f"--{role}_col={user_value!r} not found. Available columns: {list(df.columns)}")
        return user_value
    lower_to_real = {c.lower(): c for c in df.columns}
    for cand in candidates:
        if cand.lower() in lower_to_real:
            return lower_to_real[cand.lower()]
    raise ValueError(
        f"Could not infer {role} column. Please pass --{role}_col explicitly. "
        f"Available columns: {list(df.columns)}"
    )


def load_split_indices(split_npz: str) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    data = np.load(split_npz, allow_pickle=True)
    keys = set(data.files)

    def first_existing(names: Sequence[str]) -> str:
        for n in names:
            if n in keys:
                return n
        raise KeyError(f"None of {names} found in {split_npz}; available keys={sorted(keys)}")

    train_key = first_existing(["train_idx", "train_indices", "idx_train", "train", "train_index"])
    val_key = first_existing(["val_idx", "valid_idx", "validation_idx", "val_indices", "valid_indices", "idx_val", "idx_valid", "val", "valid"])
    test_key = first_existing(["test_idx", "test_indices", "idx_test", "test", "test_index"])
    return data[train_key].astype(np.int64), data[val_key].astype(np.int64), data[test_key].astype(np.int64)


def parse_seed_fold_from_path(path: str) -> Tuple[Optional[int], Optional[int]]:
    name = Path(path).name
    m = re.search(r"seed_(\d+)_fold_(\d+)", name)
    if not m:
        return None, None
    return int(m.group(1)), int(m.group(2))


def ordered_label_values(series: pd.Series) -> List[str]:
    values = [str(x) for x in pd.unique(series.astype(str))]
    # Numeric labels should remain in numeric order: 0, 1, 2...
    try:
        return [str(x) for x in sorted(values, key=lambda v: float(v))]
    except Exception:
        return sorted(values)


def infer_positive_mask_for_train_graph(labels: pd.Series, edge_labels: str, positive_labels: Optional[str]) -> np.ndarray:
    label_str = labels.astype(str)
    if edge_labels == "all":
        return np.ones(len(label_str), dtype=bool)
    if edge_labels == "positive":
        if not positive_labels:
            raise ValueError("--edge_labels positive requires --positive_labels, e.g. --positive_labels 1")
        positives = {x.strip() for x in positive_labels.split(",") if x.strip()}
        return label_str.isin(positives).to_numpy()

    # auto: binary numeric 0/1 -> only 1 is a graph edge; otherwise all non-negative-token labels are graph edges.
    uniq = set(label_str.unique())
    if uniq.issubset({"0", "1", "0.0", "1.0"}):
        return label_str.isin({"1", "1.0"}).to_numpy()
    return ~label_str.str.lower().isin(NEGATIVE_TOKENS).to_numpy()


class RandomWalkCorpus:
    """Streaming random-walk corpus for gensim Word2Vec.

    This avoids materializing num_nodes * num_walks walks in memory, which is important for
    the larger DDI datasets.
    """

    def __init__(self, adjacency: Dict[str, List[str]], walk_length: int, num_walks: int, seed: int):
        self.adjacency = adjacency
        self.walk_length = walk_length
        self.num_walks = num_walks
        self.seed = seed
        self.nodes = list(adjacency.keys())

    def __iter__(self) -> Iterator[List[str]]:
        rng = random.Random(self.seed)
        nodes = self.nodes[:]
        for walk_iter in range(self.num_walks):
            rng.shuffle(nodes)
            for node in nodes:
                yield self._walk(node, rng)

    def _walk(self, start_node: str, rng: random.Random) -> List[str]:
        walk = [start_node]
        while len(walk) < self.walk_length:
            cur = walk[-1]
            nbrs = self.adjacency.get(cur, [])
            if not nbrs:
                break
            walk.append(rng.choice(nbrs))
        return walk


def build_train_adjacency(train_df: pd.DataFrame, col_u: str, col_v: str, label_col: str,
                          edge_labels: str, positive_labels: Optional[str]) -> Dict[str, List[str]]:
    mask = infer_positive_mask_for_train_graph(train_df[label_col], edge_labels=edge_labels, positive_labels=positive_labels)
    edge_df = train_df.loc[mask, [col_u, col_v]]
    adjacency: Dict[str, List[str]] = defaultdict(list)
    skipped_self_loops = 0
    for u, v in edge_df.itertuples(index=False, name=None):
        su, sv = str(u), str(v)
        if su == sv:
            skipped_self_loops += 1
            continue
        adjacency[su].append(sv)
        adjacency[sv].append(su)
    if len(adjacency) == 0:
        raise ValueError("The train graph has no edges. Check --edge_labels / --positive_labels.")
    return dict(adjacency)


def train_word2vec_embeddings(adjacency: Dict[str, List[str]], args: argparse.Namespace, seed: int) -> Tuple[np.ndarray, Dict[str, int]]:
    corpus = RandomWalkCorpus(adjacency, walk_length=args.walk_length, num_walks=args.num_walks, seed=seed)
    model = Word2Vec(
        vector_size=args.dimensions,
        window=args.window_size,
        min_count=0,
        sg=1,
        workers=args.workers,
        epochs=args.w2v_epochs,
        seed=seed,
        sample=args.sample,
        negative=args.negative,
    )
    model.build_vocab(corpus)
    model.train(corpus, total_examples=model.corpus_count, epochs=args.w2v_epochs)

    node_to_row: Dict[str, int] = {}
    emb = np.zeros((len(model.wv.index_to_key) + 1, args.dimensions), dtype=np.float32)  # row 0 = unseen/isolated
    for i, node in enumerate(model.wv.index_to_key, start=1):
        node_to_row[node] = i
        emb[i] = model.wv[node]
    return emb, node_to_row


def map_nodes_to_embedding_rows(df: pd.DataFrame, col: str, node_to_row: Dict[str, int]) -> np.ndarray:
    # pandas.map is faster and less memory-hungry than Python loops for large CSVs.
    mapped = df[col].astype(str).map(node_to_row).fillna(0).astype(np.int64)
    return mapped.to_numpy()


class PairDataset(torch.utils.data.Dataset):
    def __init__(self, u_idx: np.ndarray, v_idx: np.ndarray, y: np.ndarray):
        self.u_idx = torch.as_tensor(u_idx, dtype=torch.long)
        self.v_idx = torch.as_tensor(v_idx, dtype=torch.long)
        self.y = torch.as_tensor(y, dtype=torch.long)

    def __len__(self) -> int:
        return int(self.y.numel())

    def __getitem__(self, idx: int):
        return self.u_idx[idx], self.v_idx[idx], self.y[idx]


class PairMLP(nn.Module):
    def __init__(self, input_dim: int, hidden_dim: int, num_classes: int, dropout: float):
        super().__init__()
        hidden2 = max(hidden_dim // 2, num_classes * 2)
        self.net = nn.Sequential(
            nn.Linear(input_dim, hidden_dim),
            nn.BatchNorm1d(hidden_dim),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(hidden_dim, hidden2),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(hidden2, num_classes),
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.net(x)


def make_pair_features(emb_tensor: torch.Tensor, u_idx: torch.Tensor, v_idx: torch.Tensor, operators: Sequence[str]) -> torch.Tensor:
    hu = emb_tensor[u_idx]
    hv = emb_tensor[v_idx]
    feats = []
    for op in operators:
        if op == "hadamard":
            feats.append(hu * hv)
        elif op == "l1":
            feats.append(torch.abs(hu - hv))
        elif op == "l2":
            feats.append((hu - hv) ** 2)
        elif op == "avg":
            feats.append((hu + hv) / 2.0)
        elif op == "concat":
            feats.append(torch.cat([hu, hv], dim=1))
        else:
            raise ValueError(f"Unknown pair operator: {op}")
    return torch.cat(feats, dim=1)


def input_dim_from_operators(dimensions: int, operators: Sequence[str]) -> int:
    total = 0
    for op in operators:
        total += 2 * dimensions if op == "concat" else dimensions
    return total


def evaluate_model(model: nn.Module, emb_tensor: torch.Tensor, dataset: PairDataset, device: torch.device,
                   batch_size: int, operators: Sequence[str], num_classes: int, class_names: List[str]) -> Tuple[Dict[str, float], np.ndarray, np.ndarray]:
    loader = torch.utils.data.DataLoader(dataset, batch_size=batch_size, shuffle=False, num_workers=0)
    model.eval()
    all_probs: List[np.ndarray] = []
    all_y: List[np.ndarray] = []
    with torch.no_grad():
        for u, v, y in loader:
            u = u.to(device, non_blocking=True)
            v = v.to(device, non_blocking=True)
            x = make_pair_features(emb_tensor, u, v, operators)
            logits = model(x)
            probs = F.softmax(logits, dim=1).detach().cpu().numpy()
            all_probs.append(probs)
            all_y.append(y.numpy())
    probs = np.concatenate(all_probs, axis=0)
    y_true = np.concatenate(all_y, axis=0)
    y_pred = probs.argmax(axis=1)

    metrics: Dict[str, float] = {
        "accuracy": float(accuracy_score(y_true, y_pred)),
        "balanced_accuracy": float(balanced_accuracy_score(y_true, y_pred)),
        "f1_macro": float(f1_score(y_true, y_pred, average="macro", zero_division=0)),
        "f1_micro": float(f1_score(y_true, y_pred, average="micro", zero_division=0)),
        "f1_weighted": float(f1_score(y_true, y_pred, average="weighted", zero_division=0)),
        "precision_macro": float(precision_score(y_true, y_pred, average="macro", zero_division=0)),
        "recall_macro": float(recall_score(y_true, y_pred, average="macro", zero_division=0)),
    }
    # AUC / AUPR need all classes present in y_true. If a tiny validation/test split misses a class, return NaN.
    try:
        if num_classes == 2:
            metrics["roc_auc_macro_ovr"] = float(roc_auc_score(y_true, probs[:, 1]))
            metrics["aupr_macro_ovr"] = float(average_precision_score(y_true, probs[:, 1]))
        else:
            y_bin = label_binarize(y_true, classes=np.arange(num_classes))
            metrics["roc_auc_macro_ovr"] = float(roc_auc_score(y_bin, probs, average="macro", multi_class="ovr"))
            metrics["aupr_macro_ovr"] = float(average_precision_score(y_bin, probs, average="macro"))
    except Exception:
        metrics["roc_auc_macro_ovr"] = float("nan")
        metrics["aupr_macro_ovr"] = float("nan")

    # Per-class F1 is useful for appendix and reviewer response.
    per_class_f1 = f1_score(y_true, y_pred, average=None, labels=np.arange(num_classes), zero_division=0)
    for i, name in enumerate(class_names):
        metrics[f"f1_class_{name}"] = float(per_class_f1[i])
    return metrics, y_true, y_pred


def train_mlp(
    emb: np.ndarray,
    train_pack: Tuple[np.ndarray, np.ndarray, np.ndarray],
    val_pack: Tuple[np.ndarray, np.ndarray, np.ndarray],
    test_pack: Tuple[np.ndarray, np.ndarray, np.ndarray],
    args: argparse.Namespace,
    num_classes: int,
    class_names: List[str],
    seed: int,
) -> Tuple[Dict[str, float], Dict[str, float], int, Optional[Dict[str, torch.Tensor]], np.ndarray, np.ndarray]:
    device = torch.device(args.device if args.device == "cpu" or torch.cuda.is_available() else "cpu")
    operators = [x.strip() for x in args.pair_operators.split(",") if x.strip()]
    input_dim = input_dim_from_operators(args.dimensions, operators)

    train_ds = PairDataset(*train_pack)
    val_ds = PairDataset(*val_pack)
    test_ds = PairDataset(*test_pack)

    generator = torch.Generator()
    generator.manual_seed(seed)
    train_loader = torch.utils.data.DataLoader(
        train_ds,
        batch_size=args.batch_size,
        shuffle=True,
        num_workers=0,
        generator=generator,
        pin_memory=(device.type == "cuda"),
    )

    emb_tensor = torch.as_tensor(emb, dtype=torch.float32, device=device)
    model = PairMLP(input_dim=input_dim, hidden_dim=args.hidden_dim, num_classes=num_classes, dropout=args.dropout).to(device)
    optimizer = torch.optim.AdamW(model.parameters(), lr=args.lr, weight_decay=args.weight_decay)

    if args.class_weight == "balanced":
        counts = np.bincount(train_pack[2], minlength=num_classes).astype(np.float64)
        weights = counts.sum() / np.maximum(counts, 1.0) / num_classes
        criterion = nn.CrossEntropyLoss(weight=torch.as_tensor(weights, dtype=torch.float32, device=device))
    else:
        criterion = nn.CrossEntropyLoss()

    best_score = -float("inf")
    best_epoch = 0
    best_state: Optional[Dict[str, torch.Tensor]] = None
    patience_left = args.patience

    for epoch in range(1, args.mlp_epochs + 1):
        model.train()
        running_loss = 0.0
        seen = 0
        for u, v, y in train_loader:
            u = u.to(device, non_blocking=True)
            v = v.to(device, non_blocking=True)
            y = y.to(device, non_blocking=True)
            x = make_pair_features(emb_tensor, u, v, operators)
            logits = model(x)
            loss = criterion(logits, y)
            optimizer.zero_grad(set_to_none=True)
            loss.backward()
            optimizer.step()
            running_loss += float(loss.detach().cpu()) * int(y.numel())
            seen += int(y.numel())

        val_metrics, _, _ = evaluate_model(
            model, emb_tensor, val_ds, device=device, batch_size=args.eval_batch_size,
            operators=operators, num_classes=num_classes, class_names=class_names,
        )
        score = val_metrics[args.monitor]
        print(
            f"Epoch {epoch:03d} | train_loss={running_loss / max(seen, 1):.6f} | "
            f"val_{args.monitor}={score:.6f} | val_acc={val_metrics['accuracy']:.6f}",
            flush=True,
        )
        if score > best_score + args.min_delta:
            best_score = score
            best_epoch = epoch
            best_state = {k: v.detach().cpu().clone() for k, v in model.state_dict().items()}
            patience_left = args.patience
        else:
            patience_left -= 1
            if patience_left <= 0:
                print(f"Early stopping at epoch {epoch}; best_epoch={best_epoch}, best_val_{args.monitor}={best_score:.6f}")
                break

    if best_state is not None:
        model.load_state_dict(best_state)
    val_metrics, _, _ = evaluate_model(
        model, emb_tensor, val_ds, device=device, batch_size=args.eval_batch_size,
        operators=operators, num_classes=num_classes, class_names=class_names,
    )
    test_metrics, y_true, y_pred = evaluate_model(
        model, emb_tensor, test_ds, device=device, batch_size=args.eval_batch_size,
        operators=operators, num_classes=num_classes, class_names=class_names,
    )
    return val_metrics, test_metrics, best_epoch, best_state, y_true, y_pred


def save_json(path: Path, obj: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        json.dump(obj, f, indent=2, ensure_ascii=False)


def main() -> None:
    parser = argparse.ArgumentParser(description="Train Node2Vec + MLP on one shared DDI split.")
    parser.add_argument("--dataset", required=True)
    parser.add_argument("--prepared_csv", required=True)
    parser.add_argument("--split_npz", required=True)
    parser.add_argument("--output_dir", required=True)
    parser.add_argument("--drug1_col", default=None)
    parser.add_argument("--drug2_col", default=None)
    parser.add_argument("--label_col", default=None)

    parser.add_argument("--edge_labels", choices=["auto", "all", "positive"], default="auto",
                        help="Which TRAIN labels are used as graph edges for node2vec. auto: binary 0/1 uses only 1; multiclass uses all non-negative-token labels.")
    parser.add_argument("--positive_labels", default=None,
                        help="Comma-separated labels used as graph edges when --edge_labels positive.")

    parser.add_argument("--dimensions", type=int, default=128)
    parser.add_argument("--walk_length", type=int, default=40)
    parser.add_argument("--num_walks", type=int, default=5)
    parser.add_argument("--window_size", type=int, default=10)
    parser.add_argument("--w2v_epochs", type=int, default=3)
    parser.add_argument("--workers", type=int, default=4)
    parser.add_argument("--sample", type=float, default=1e-3)
    parser.add_argument("--negative", type=int, default=5, help="Word2Vec negative samples, not DDI negative sampling.")

    parser.add_argument("--pair_operators", default="hadamard,l1")
    parser.add_argument("--hidden_dim", type=int, default=256)
    parser.add_argument("--dropout", type=float, default=0.3)
    parser.add_argument("--lr", type=float, default=1e-3)
    parser.add_argument("--weight_decay", type=float, default=1e-4)
    parser.add_argument("--batch_size", type=int, default=8192)
    parser.add_argument("--eval_batch_size", type=int, default=32768)
    parser.add_argument("--mlp_epochs", type=int, default=80)
    parser.add_argument("--patience", type=int, default=10)
    parser.add_argument("--monitor", choices=["f1_macro", "accuracy", "balanced_accuracy", "roc_auc_macro_ovr", "aupr_macro_ovr"], default="f1_macro")
    parser.add_argument("--min_delta", type=float, default=1e-5)
    parser.add_argument("--class_weight", choices=["none", "balanced"], default="balanced")

    parser.add_argument("--device", default="cuda", help="cuda or cpu")
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--seed_from_split", action="store_true", help="Use seed parsed from seed_<seed>_fold_<fold>.npz.")
    parser.add_argument("--deterministic_torch", action="store_true")
    parser.add_argument("--save_embeddings", action="store_true")
    parser.add_argument("--save_predictions", action="store_true")
    args = parser.parse_args()

    split_seed, split_fold = parse_seed_fold_from_path(args.split_npz)
    seed = split_seed if args.seed_from_split and split_seed is not None else args.seed
    fold = split_fold
    set_global_seed(seed, deterministic_torch=args.deterministic_torch)

    start = time.time()
    print(f"Loading prepared CSV: {args.prepared_csv}", flush=True)
    df = pd.read_csv(args.prepared_csv)
    col_u = pick_column(df, ID_COL_CANDIDATES_1, "drug1", args.drug1_col)
    col_v = pick_column(df, ID_COL_CANDIDATES_2, "drug2", args.drug2_col)
    label_col = pick_column(df, LABEL_COL_CANDIDATES, "label", args.label_col)
    print(f"Columns: drug1={col_u}, drug2={col_v}, label={label_col}", flush=True)

    train_idx, val_idx, test_idx = load_split_indices(args.split_npz)
    n_rows = len(df)
    for name, idx in [("train", train_idx), ("val", val_idx), ("test", test_idx)]:
        if idx.min(initial=0) < 0 or idx.max(initial=0) >= n_rows:
            raise IndexError(f"{name} indices out of range for {args.prepared_csv}: n_rows={n_rows}")
    train_df = df.iloc[train_idx].reset_index(drop=True)
    val_df = df.iloc[val_idx].reset_index(drop=True)
    test_df = df.iloc[test_idx].reset_index(drop=True)

    class_names = ordered_label_values(df[label_col])
    label_to_id = {name: i for i, name in enumerate(class_names)}
    num_classes = len(class_names)
    print(f"Classes ({num_classes}): {label_to_id}", flush=True)
    if num_classes < 2:
        raise ValueError("Need at least two classes for classification.")

    print("Building TRAIN-only graph for node2vec...", flush=True)
    adjacency = build_train_adjacency(train_df, col_u, col_v, label_col, args.edge_labels, args.positive_labels)
    num_graph_nodes = len(adjacency)
    num_graph_edges_undir = sum(len(v) for v in adjacency.values()) // 2
    print(f"Train graph: nodes={num_graph_nodes}, undirected_edges={num_graph_edges_undir}", flush=True)

    print("Training node2vec / Word2Vec embeddings...", flush=True)
    emb, node_to_row = train_word2vec_embeddings(adjacency, args, seed=seed)
    print(f"Embedding matrix: {emb.shape}; missing-row index=0", flush=True)

    def pack(split_df: pd.DataFrame) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
        u_rows = map_nodes_to_embedding_rows(split_df, col_u, node_to_row)
        v_rows = map_nodes_to_embedding_rows(split_df, col_v, node_to_row)
        y = split_df[label_col].astype(str).map(label_to_id).to_numpy(dtype=np.int64)
        return u_rows, v_rows, y

    train_pack = pack(train_df)
    val_pack = pack(val_df)
    test_pack = pack(test_df)

    def missing_rate(pack_tuple: Tuple[np.ndarray, np.ndarray, np.ndarray]) -> float:
        u, v, _ = pack_tuple
        return float(((u == 0) | (v == 0)).mean())

    print(
        f"Missing embedding pair rate: train={missing_rate(train_pack):.4f}, "
        f"val={missing_rate(val_pack):.4f}, test={missing_rate(test_pack):.4f}",
        flush=True,
    )

    print("Training MLP classifier...", flush=True)
    val_metrics, test_metrics, best_epoch, best_state, y_true, y_pred = train_mlp(
        emb, train_pack, val_pack, test_pack, args, num_classes=num_classes, class_names=class_names, seed=seed
    )

    split_name = f"seed_{split_seed if split_seed is not None else seed}_fold_{fold if fold is not None else 'NA'}"
    out_dir = Path(args.output_dir) / args.dataset / split_name
    out_dir.mkdir(parents=True, exist_ok=True)

    result = {
        "method": "Node2Vec+MLP",
        "dataset": args.dataset,
        "seed": int(split_seed if split_seed is not None else seed),
        "fold": None if fold is None else int(fold),
        "prepared_csv": str(Path(args.prepared_csv)),
        "split_npz": str(Path(args.split_npz)),
        "split_sizes": {"train": int(len(train_df)), "val": int(len(val_df)), "test": int(len(test_df))},
        "columns": {"drug1": col_u, "drug2": col_v, "label": label_col},
        "label_to_id": label_to_id,
        "train_graph": {
            "source": "train split only",
            "edge_labels": args.edge_labels,
            "positive_labels": args.positive_labels,
            "nodes": int(num_graph_nodes),
            "undirected_edges": int(num_graph_edges_undir),
        },
        "node2vec": {
            "dimensions": args.dimensions,
            "walk_length": args.walk_length,
            "num_walks": args.num_walks,
            "window_size": args.window_size,
            "w2v_epochs": args.w2v_epochs,
            "workers": args.workers,
            "word2vec_negative": args.negative,
            "sample": args.sample,
        },
        "mlp": {
            "pair_operators": args.pair_operators,
            "hidden_dim": args.hidden_dim,
            "dropout": args.dropout,
            "lr": args.lr,
            "weight_decay": args.weight_decay,
            "batch_size": args.batch_size,
            "mlp_epochs_max": args.mlp_epochs,
            "patience": args.patience,
            "monitor": args.monitor,
            "class_weight": args.class_weight,
            "best_epoch": int(best_epoch),
        },
        "missing_embedding_pair_rate": {
            "train": missing_rate(train_pack),
            "val": missing_rate(val_pack),
            "test": missing_rate(test_pack),
        },
        "val_metrics": val_metrics,
        "test_metrics": test_metrics,
        "runtime_sec": float(time.time() - start),
    }
    save_json(out_dir / "metrics.json", result)

    flat = {
        "method": "Node2Vec+MLP",
        "dataset": args.dataset,
        "seed": result["seed"],
        "fold": result["fold"],
        "best_epoch": best_epoch,
        "runtime_sec": result["runtime_sec"],
        "train_size": len(train_df),
        "val_size": len(val_df),
        "test_size": len(test_df),
        "train_graph_nodes": num_graph_nodes,
        "train_graph_edges": num_graph_edges_undir,
        "missing_train": result["missing_embedding_pair_rate"]["train"],
        "missing_val": result["missing_embedding_pair_rate"]["val"],
        "missing_test": result["missing_embedding_pair_rate"]["test"],
    }
    for k, v in test_metrics.items():
        flat[f"test_{k}"] = v
    for k, v in val_metrics.items():
        flat[f"val_{k}"] = v
    pd.DataFrame([flat]).to_csv(out_dir / "metrics.csv", index=False, encoding="utf-8-sig")

    if args.save_embeddings:
        np.savez_compressed(out_dir / "node2vec_embeddings.npz", emb=emb, nodes=np.array(list(node_to_row.keys()), dtype=object))
    if args.save_predictions:
        pd.DataFrame({"y_true": y_true, "y_pred": y_pred}).to_csv(out_dir / "test_predictions.csv", index=False)

    print("Done.")
    print(json.dumps({"output": str(out_dir), "test_metrics": test_metrics}, indent=2, ensure_ascii=False), flush=True)


if __name__ == "__main__":
    main()
